### ISSUE TITLE
CUDA not available within plugins using PyTorch

### ISSUE THREAD

**Issue by SpiderBraids** [jbarlow83/OCRmyPDF#818]
**Describe the bug**
Whenever I try to use CUDA with PyTorch within an OCRmyPDF plugin, `torch.cuda.is_available()` returns False, forcing PyTorch networks to be run using the CPU, thus significantly impacting performance compared to GPU. Meanwhile, outside of OCRmyPDF, CUDA is available, and CUDA runs perfectly fine when called in a separate program, even when called as part of a subprocess within a plugin.

**To Reproduce**
Write a plugin with `import torch` and `print(torch.cuda.is_available())`; it will print out False
Write a separate python file with `import torch` and `print(torch.cuda.is_available())`, and then a plugin that uses `subprocess.run` to run the python file as a separate process; it will print out True

**Expected behavior**
I expected to be able to run CUDA directly within the plugin instead of having to execute it as a separate program (for example, to allow objects created within CUDA-powered code to be reused)

**System**
I am running OCRmyPDF within a Docker with the following specifications:
 - OS: Ubuntu
 - Python version: 3.7.10
 - OCRmyPDF version: Pulled from Github 15 July 2021, compiled
(+ PyTorch 1.9.0 and Torchvision 0.10.0)

**Comment by jbarlow83** [comment]
OCRmyPDF does not do anything to prevent the use of GPU or CUDA that I am aware and does not use them internally.

Possibly, the version of PyTorch in your ocrmypdf virtual Python environment does not support CUDA. `subprocess.run` might break out of the ocrmypdf virtual environment and use the system Python. Try `subprocess.run([sys.executable, ...])` to ensure you are running the same virtual environment.

It may also be that Docker is preventing the use of CUDA.

You might also need to create a new executor plugin that replaces Python's standard multiprocessing pytorch's multiprocessing. I can help with that if it turns out to be necessary since it may be of general interest.
https://pytorch.org/docs/stable/notes/multiprocessing.html . A quick test would be `ocrmypdf --use-threads` which uses a threaded executor instead of multiprocessing.
